[project]
name = "python-weather-app-with-poetry"
version = "1.0.0"
description = "A Simple weather application built with Python and Poetry"
authors = [
    {name = "Raghu",email = "raghu@abcorp.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "colorama (==0.4.4)",
    "requests (==2.26.0)",
    "flask (==1.0.2)",
    "waitress (==2.0.0)",
    "agpt (==0.2.2)",
    "django (==4.2.18)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
